# Generated by Django 5.1.1 on 2025-07-05 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0017_remove_coopstatehistory_new_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopstatehistory',
            name='new_state',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='new_history', to='StoneFlow.step'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coopstatehistory',
            name='previous_state',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='prev_history', to='StoneFlow.step'),
            preserve_default=False,
        ),
    ]
