# Generated by Django 5.1.1 on 2025-07-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoneFlow', '0018_coopstatehistory_new_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coopstatehistory',
            name='new_state',
        ),
        migrations.RemoveField(
            model_name='coopstatehistory',
            name='previous_state',
        ),
    ]
